import { SyncStageMessageType } from './SyncStageMessageType';

export enum RequestResponseMap {
  Ping = SyncStageMessageType.Pong,
  ProvisionRequest = SyncStageMessageType.ProvisionResponse,
  CreateSessionRequest = SyncStageMessageType.CreateSessionResponse,
  JoinRequest = SyncStageMessageType.JoinResponse,
  LeaveRequest = SyncStageMessageType.LeaveResponse,
  SessionRequest = SyncStageMessageType.SessionResponse,
  ChangeReceiverVolumeRequest = SyncStageMessageType.ChangeReceiverVolumeResponse,
  GetReceiverVolumeRequest = SyncStageMessageType.GetReceiverVolumeResponse,
  ToggleMicrophoneRequest = SyncStageMessageType.ToggleMicrophoneResponse,
  IsMicrophoneMutedRequest = SyncStageMessageType.IsMicrophoneMutedResponse,
  GetReceiverMeasurementsRequest = SyncStageMessageType.GetReceiverMeasurementsResponse,
  GetTransmitterMeasurementsRequest = SyncStageMessageType.GetTransmitterMeasurementsResponse,
  BestAvailableServerRequest = SyncStageMessageType.BestAvailableServerResponse,
  ServerInstancesRequest = SyncStageMessageType.ServerInstancesResponse,
  StartRecordingRequest = SyncStageMessageType.StartRecordingResponse,
  StopRecordingRequest = SyncStageMessageType.StopRecordingResponse,
  UpdateTokenRequest = SyncStageMessageType.UpdateTokenResponse,
  VersionRequest = SyncStageMessageType.VersionResponse,
  GetSessionSettingsRequest = SyncStageMessageType.GetSessionSettingsResponse,
  SetInputDeviceRequest = SyncStageMessageType.SetInputDeviceResponse,
  SetOutputDeviceRequest = SyncStageMessageType.SetOutputDeviceResponse,
  SetLatencyOptimizationLevelRequest = SyncStageMessageType.SetLatencyOptimizationLevelResponse,
  SetNoiseCancellationRequest = SyncStageMessageType.SetNoiseCancellationResponse,
  SetDisableGainRequest = SyncStageMessageType.SetDisableGainResponse,
  SetDirectMonitorRequest = SyncStageMessageType.SetDirectMonitorResponse,
}
