enum SyncStageSDKErrorCode {
  'TOKEN_EXPIRED' = -2002,
  'SYNCSTAGE_OPENED_IN_ANOTHER_TAB' = -2001,
  'NOT_IN_SESSION' = -1001,
  'API_UNAUTHORIZED' = -1000,

  'STUDIO_SERVER_NOT_FOUND' = -12,
  'SYNCSTAGE_SERVICE_COMMUNICATION_ERROR' = -11,
  'TIMEOUT_ERROR' = -10,
  'UNKNOWN_ERROR' = -1,

  'OK' = 0,
  'CONFIGURATION_ERROR' = 1,
  'API_ERROR' = 2,
  'STREAM_DOES_NOT_EXIST' = 3,
  'BAD_VOLUME_VALUE' = 4,
  'NO_ZONE_AVAILABLE' = 5,
  'NO_STUDIO_SERVER_AVAILABLE' = 6,
  'NO_INPUT_DEVICE' = 7,
}

export default SyncStageSDKErrorCode;
